/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#004ac6",
        "surface-tint": "#0053db",
        "on-primary-container": "#eeefff",
        "on-tertiary-fixed": "#002113",
        surface: "#f9f9ff",
        "surface-container-high": "#e5e8f4",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eef0fc",
        "secondary-container": "#8a4cfc",
        "on-primary-fixed": "#00174b",
        "on-error-container": "#93000a",
        "secondary-fixed": "#eaddff",
        "outline-variant": "#c3c6d7",
        "primary-container": "#2563eb",
        "on-secondary-fixed": "#25005a",
        "surface-container": "#ebedfa",
        error: "#ba1a1a",
        "surface-dim": "#d7dae5",
        outline: "#737686",
        "surface-container-low": "#f1f3ff",
        "primary-fixed-dim": "#b4c5ff",
        "secondary-fixed-dim": "#d2bbff",
        "on-background": "#181c24",
        "surface-container-highest": "#dfe2ee",
        "surface-bright": "#f9f9ff",
        "on-primary": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "inverse-surface": "#2c3039",
        "tertiary-container": "#007d55",
        background: "#f9f9ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#bdffdb",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-tertiary-fixed-variant": "#005236",
        "on-error": "#ffffff",
        secondary: "#712ae2",
        "primary-fixed": "#dbe1ff",
        "surface-variant": "#dfe2ee",
        "on-secondary-container": "#fffbff",
        "on-secondary": "#ffffff",
        tertiary: "#006242",
        "on-surface-variant": "#434655",
        "on-surface": "#181c24",
        "tertiary-fixed": "#6ffbbe"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
